server:
  port: 8085
  servlet:
    context-path: /clinic-management-service
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  database:
    driverClassName: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://localhost:5432/cmdb
    username: admin
    password: cmdb2023!
  liquibase:
    enabled: true
    change-log: "classpath:db/changelog/db.changelog-master.yaml"
logging:
  excluded-requests: /actuator/health, /swagger-ui, /api-docs
springdoc:
  swagger-ui:
    path: /swagger-ui
    operationsSorter: method
    tagsSorter: alpha

# -----------------------------------------------------------------#
# Actuator configuration
management:
  endpoint:
    enabled-by-default: false
    health:
      show-details: always
      enabled: true
      info.enabled: true
  health:
    defaults.enabled: true
    db.enabled: true